name: tnnt

on:
  push:
    branches: [ master ]
    tags:
      - '*' # won't work on tags containing /
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      HINTS_FILE: linux-debug.gha
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: ./sys/unix/setup.sh sys/unix/hints/$HINTS_FILE
    - name: make all
      run: make all
    - name: make install
      run: make install

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
